version: "3.8"

services:
  api:
    build: .
    container_name: mukti_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mukti_network

  db:
    image: postgres:latest
    container_name: mukti_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mukti
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mukti_network

networks:
  mukti_network:
    driver: bridge

volumes:
  db_data:
